apiVersion: v1
kind: Pod
metadata:
  name: cm-var-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command: [ "/bin/sh", "-c", "echo $(LEVEL) $(TYPE)" ]
      env:
        - name: LEVEL
          valueFrom:
            configMapKeyRef:
              name: myconfigmap
              key: special.level
        - name: TYPE
          valueFrom:
            configMapKeyRef:
              name: myconfigmap
              key: special.type
  restartPolicy: Never
